blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/SBb2wGgqKR
    about: Please ask any questions here
  - name: Enterprise Questions
    url: opensource@getsynth.com
    about: Please get in touch for any enterprise related questions
