[package]
name = "synth-gen"
version = "0.4.0"
authors = [
  "Damien Broka <damien@getsynth.com>",
  "Christos Hadjiaslanis <christos@getsynth.com>"
]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
serde_json = "1.0"

[features]
default = [ ]
faker = [ "fake" ]
shared = [ ]

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
rand = "0.8.3"

fake = { version = "2.2.3", optional = true }

anyhow = { version = "1.0.34" }
