[package]
name = "synth-gen"
version = "0.4.1"
authors = [
  "Damien Broka <damien@getsynth.com>",
  "Christos Hadjiaslanis <christos@getsynth.com>"
]
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
serde_json = "1.0"

[features]
default = [ ]
faker = [ "fake" ]
shared = [ ]

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
rand = "0.8.3"
ordered-float = { version = "2.0", features = ["serde", "rand"] }
fake = { version = "=2.4.1", features = ["http"], optional = true }
