[package]
name = "synth"
version = "0.5.0"
authors = [
  "Damien Broka <damien@getsynth.com>",
  "Christos Hadjiaslanis <christos@getsynth.com>",
  "Andre Bogus <andre@getsynth.com>"
]
edition = "2018"
license = "Apache-2.0"

[features]
api = [ "tide", "reqwest", "synth-core/api" ]

[[bench]]
name = "bench"
harness = false

[build-dependencies]
git2 = "0.13.20"

[dev-dependencies]
lazy_static = "1.4.0"
tempfile = "3.1.0"
iai = "0.1"

[dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
posthog-rs = "0.1.3"

colored = "2.0.0"
anyhow = "1.0.32"

structopt = "0.3.18"

log = "0.4.11"
env_logger = "0.7.1"

num_cpus = "1.0"
sysinfo = "0.15.2"
strsim = "0.10.0"

async-std = { version = "1.6.4", features = [ "attributes", "unstable" ] }
tide = { version = "0.13.0", optional = true }

reqwest = { version = "0.10", features = ["blocking", "json"], optional = true } # only used by `rlog`

fs2 = "0.4.3"
diesel = { version = "1.4.5", features = [ "sqlite", "chrono" ], optional = true }
diesel_migrations = { version = "1.4.0", optional = true}

chrono = "0.4.18"
regex = "1.3.9"
rand = "0.8.3"
ctrlc = { version = "3.0", features = ["termination"] }

synth-core = { path = "../core" }
synth-gen = { path = "../gen" }

postgres = { version = "0.19.0", features = ["with-chrono-0_4"] }
rust_decimal = { version = "1.10.3", features = ["db-postgres"] }
indicatif = "0.15.0"

dirs = "3.0.2"
uuid = { version = "0.8.2", features = ["v4"] }
mongodb = {version = "1.2.1", features = ["sync"] , default-features = false}
