name: synth-test-examples

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  RUSTFLAGS: "-D warnings"

jobs:
  test_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo +nightly install --debug --path=synth
      - run: |
          bash "${GITHUB_WORKSPACE}/.github/workflows/scripts/test_examples.sh" ${GITHUB_WORKSPACE}/examples
