name: synth ci/cd

on:
  pull_request:
    branches:
      - master

env:
  RUSTFLAGS: "-D warnings"

jobs:
  tests:
    name: synth tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo test
