name: synth-errors

on:
  push:
    branches: [master]
    paths: ["**/*.rs", "synth/testing_harness/errors/**"]
  pull_request:
    branches: [master]
    paths: ["**/*.rs", "synth/testing_harness/errors/**"]

  workflow_dispatch:

env:
  RUSTFLAGS: "-D warnings"

jobs:
  e2e_tests_postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo +nightly install --locked --debug --path=synth
      - run: ./e2e.sh
        working-directory: synth/testing_harness/errors
