name: synth ci/cd

on:
  pull_request:
    branches:
      - master

jobs:

  tests:
    name: synth tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-05-17
      - run: cargo +nightly-2021-05-17 test
