name: synth-mysql

on:
  push:
    branches: [ master ]
    paths: [ "**/*.rs", "synth/testing_harness/mysql/**" ]
  pull_request:
    branches: [ master ]
    paths: [ "**/*.rs", "synth/testing_harness/mysql/**" ]

  workflow_dispatch:

env:
  RUSTFLAGS: "-D warnings"

jobs:
  e2e_tests_mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mysecretpassword
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --name mysql-synth-harness
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      mariadb:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: mysecretpassword
          MYSQL_DATABASE: test_db
        ports:
          - 3307:3306
        options: >-
          --name mariadb-synth-harness
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      matrix:
        include:
          - db: mysql
            port: 3306
          - db: mariadb
            port: 3307
    steps:
      - uses: actions/checkout@v2
      ## Set env. variables for this job
      - run: |
          echo "PORT=${{ matrix.port }}" >> $GITHUB_ENV
          echo "SCHEME=${{ matrix.db }}" >> $GITHUB_ENV
      - run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends jq
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install --locked --debug --path=synth
      - run: ./e2e.sh test-generate
        working-directory: synth/testing_harness/mysql
      - run: ./e2e.sh test-import
        working-directory: synth/testing_harness/mysql
      - run: ./e2e.sh test-warnings
        working-directory: synth/testing_harness/mysql
